---
name: Build Container

"on":
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -  # https://github.com/docker/login-action/#github-container-registry
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # don't log in if we're not going to push!
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          install: true
      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          push:  ${{ github.ref == 'refs/heads/main' }}
          platforms: "linux/amd64,linux/arm64"
          # https://github.com/docker/build-push-action/issues/254
          tags: ghcr.io/yaleman/kubectl-with-jq:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: GITHUB_SHA=${GITHUB_SHA}
